workflows:
  ios-workflow:
    name: iOS Workflow1
    environment:
      groups:
        - app_store_credentials
        - certificate_credentials
      vars:
        XCODE_PROJECT: "Aviapilot.xcodeproj"
        XCODE_SCHEME: "Aviapilot"
        BUNDLE_ID: "com.hamasrl.avipilot"
        NSE_BUNDLE_ID: "com.hamasrl.avipilot.OneSignalNotificationServiceExtension"  # проверь точный идентификатор в Xcode
        APP_STORE_APPLE_ID: 6749861223
      xcode: latest
      cocoapods: default

    triggering:
      events: [push, tag, pull_request]
      branch_patterns:
        - pattern: "develop"
          include: true
          source: true

    scripts:
      - name: Set up keychain
        script: keychain initialize

      - name: Fetch signing files (app + NSE)
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --platform=IOS --create --certificate-key-password='232425'
          app-store-connect fetch-signing-files "$NSE_BUNDLE_ID" --type IOS_APP_STORE --platform=IOS --create --certificate-key-password='232425'

      - name: Use system default keychain
        script: keychain add-certificates

      - name: Apply provisioning profiles to Xcode project
        script: xcode-project use-profiles

      - name: Increment build number safely
        script: |
          LATEST=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID" || echo 0)
          agvtool new-version -all $((LATEST + 1))

      - name: Build ipa for distribution
        script: |
          if [ -d "Aviapilot.xcworkspace" ]; then
            xcode-project build-ipa --workspace "Aviapilot.xcworkspace" --scheme "$XCODE_SCHEME"
          else
            xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
          fi

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
      email:
        recipients: [radcabna@gmail.com]
        notify:
          success: true
          failure: true
      slack:
        channel: "#builds"
        notify_on_build_start: true
        notify:
          success: false
          failure: false
